language: python
python:
  - "3.7"
  - "3.7-dev"
  - "nightly"
matrix:
  include:
    - python: 2.7
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true      
before_script:
  - cd tests
script:
  - vcr_ottawa
