language: python
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
before_script:
  - pip3 install vcrpy
  - pip3 install requests
  - cd tests
script:
  - python3 vcr_ottawa.py
